---
- name: Remove old GitHub CLI GPG key
  ansible.builtin.file:
    path: /usr/share/keyrings/githubcli-archive-keyring.gpg
    state: absent
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Add GitHub CLI GPG key on Debian-based systems
  ansible.builtin.shell:
    cmd: >-
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg
      | dd of=/etc/apt/keyrings/githubcli-archive-keyring.gpg
    creates: /etc/apt/keyrings/githubcli-archive-keyring.gpg
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Add GitHub CLI apt repository on Debian-based systems
  ansible.builtin.copy:
    content: >-
      deb [arch={{ ansible_facts['architecture'] | regex_replace('x86_64', 'amd64') }}
      signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg]
      https://cli.github.com/packages stable main
    dest: /etc/apt/sources.list.d/github-cli.list
  become: true
  register: _gh_repo
  when: ansible_facts['os_family'] == 'Debian'

- name: Update apt cache after GitHub CLI repository change
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: _gh_repo is changed

- name: Add GitHub CLI dnf repository on RedHat-based systems
  ansible.builtin.yum_repository:
    name: gh-cli
    description: packages for the GitHub CLI
    baseurl: https://cli.github.com/packages/rpm
    gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059
    gpgcheck: true
    repo_gpgcheck: true
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Git
  ansible.builtin.package:
    name: git
    state: present
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Install GitHub CLI
  ansible.builtin.package:
    name: gh
    state: present
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Install Git completion scripts
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/{{ item }}"
    dest: "{{ ansible_facts['env'].HOME }}/.{{ item }}"
  with_items:
    - git-completion.bash
    - git-completion.zsh

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: .gitconfig
    dest: "{{ ansible_facts['env'].HOME }}/.gitconfig"

- name: Create .gitconfig.local
  ansible.builtin.template:
    src: .gitconfig.local.j2
    dest: "{{ ansible_facts['env'].HOME }}/.gitconfig.local"
    force: false
